 /*defining all the constants require for gridsheet*/
    var CONSTANTS={
    'PIXEL_SUFFIX':'px',
    'EM_SUFFIX':'em',
    'PERCENTAGE_SUFFIX':'%',
    'ONEPX2EM':0.167,
    'CHROME_BROWSER':'Chrome',
    'SHEET_PREFIX':'Sheet ',
    'CELL_LABEL_SEPARATOR':'-',
    'COLUMN_NAME_CHARACTERS':'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'OPTIMAL_ROWS':100,
    'OPTIMAL_COLUMNS':10,
    'CELL_CSS_PREFIX':'cell',
    'CSS_NAMING_SEPARATOR':'_',
    'SHEET_CSS_PREFIX':'sheetnum',
    'DATATYPE_TEXT':'text',
    'DATATYPE_NUMBER':'number',
    'DATATYPE_DATE':'date',
    'SHEET_BUTTON_WIDTH':100, /*100 pixels*/
    'SCROLL_TOP_OFFSET':0,
    'SCROLL_LEFT_OFFSET':-16,
    'DUMMY_TOP_BAR_Z_INDEX':100,
    'GRIDSHEET_CSS_SHEET':'gridsheet_sheet',
    'CSS_GRIDSHEET_DOCUMENT_NAME':'gridsheet_document_name',
    'GRIDSHEET_DEFAULT_DOCUMENT_NAME_PLACEHOLDER':'Document Name',
    'CSS_DOCUMENT_CONTAINER':'gridsheet_document_container',
    'CSS_GRIDSHEET_TOOLBAR':'gridsheet_toolbar',
    'CSS_GRIDSHEET_CELL':'gridsheet_cell',
    'CSS_GRIDSHEET_DUMMY_TOPBAR':'gridsheet_dummy_topbar'
    };